apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: java-microservices
type: Opaque
stringData:
  DATABASE_USER: user_user
  DATABASE_PASSWORD: user_pass
  JWT_SECRET: minhachavesupersecretaasuperseguraa1234567890abcdefghijklmn