apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: java-microservices
data:
  DATABASE_HOST: user-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: user_db
  DATABASE_URL: jdbc:postgresql://user-db:5432/user_db
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: admin
  RABBITMQ_PASS: admin
  RABBITMQ_EXCHANGE: user.exchange
  RABBITMQ_QUEUE: user.queue.user
  RABBITMQ_ROUTING_KEY: user.*