version: '3.8'

networks:
  boxsystem-net:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: auth-db-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boxsystem-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - boxsystem-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/auth_db
      DATABASE_USER: auth_user
      DATABASE_PASSWORD: auth_pass
      JWT_SECRET: minhachavesupersecretaasuperseguraa1234567890abcdefghijklmn
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
      RABBITMQ_EXCHANGE: user.events.v1
    networks:
      - boxsystem-net
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: minhachavesupersecretaasuperseguraa1234567890abcdefghijklmn
    networks:
      - boxsystem-net
    depends_on:
      - auth-service

volumes:
  postgres_data:
