apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: java-microservices
data:
  DATABASE_HOST: product-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: product_db
  DATABASE_URL: jdbc:postgresql://product-db:5432/product_db
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: admin
  RABBITMQ_PASS: admin
  RABBITMQ_EXCHANGE: user.exchange
  RABBITMQ_QUEUE: user.queue.product
  RABBITMQ_ROUTING_KEY: user.*