apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: java-microservices
type: Opaque
stringData:
  DATABASE_USER: product_user
  DATABASE_PASSWORD: product_pass
  JWT_SECRET: minhachavesupersecretaasuperseguraa1234567890abcdefghijklmn