apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: java-microservices
type: Opaque
stringData:
  DATABASE_USER: auth_user
  DATABASE_PASSWORD: auth_pass
  JWT_SECRET: minhachavesupersecretaasuperseguraa1234567890abcdefghijklmn