apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: java-microservices
data:
  DATABASE_HOST: auth-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: auth_db
  DATABASE_URL: jdbc:postgresql://auth-db:5432/auth_db
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: admin
  RABBITMQ_PASS: admin
  RABBITMQ_EXCHANGE: user.exchange
  RABBITMQ_QUEUE: user.queue
  RABBITMQ_ROUTING_KEY: user.*