apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  namespace: java-microservices
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: angular-app